# Training Pipeline

# Imports
## Pip Packages

In [1]:
import os
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

if not os.path.exists('data'):
    new_directory_path = "..\\..\\"
    os.chdir(new_directory_path)

from src.datasets import FreeViewInMemory, seq2seq_jagged_collate_fn, seq2seq_padded_collate_fn
from src.model import PathModel
import numpy as np

# Training

In [2]:
# TODO Implement Strategy and Builder pattern
datasetv2 = FreeViewInMemory(sample_size= 13,log = True, start_index=2)
model = PathModel(input_dim = 3,
                  output_dim = 3,
                  n_encoder = 2,
                  n_decoder = 2,
                  model_dim = 256,
                  total_dim = 256,
                  n_heads = 4,
                  ff_dim = 512,
                  max_pos_enc=15,
                  max_pos_dec=26)

dataloader = DataLoader(datasetv2, batch_size=128, shuffle=True, num_workers=0, collate_fn= seq2seq_padded_collate_fn)
# for batch in tqdm(dataloader):
for batch in dataloader:
    x,x_mask,y, y_mask, fixation_len = batch
    break

# model = torch.compile(model)
reg_out,cls_out = model(x,y, x_mask, y_mask)    

Data loaded in memory
input mask
target mask


In [3]:
def compute_loss(reg_out,cls_out, y, attn_mask, fixation_len, cls_weigth = .5):
    criterion_reg = torch.nn.MSELoss()
    criterion_cls = torch.nn.BCEWithLogitsLoss()
    cls_targets = torch.zeros(cls_out.size(), dtype = torch.float32)
    batch_idx = torch.arange(cls_targets.size()[0])
    cls_targets[batch_idx,fixation_len] = 1.0
    cls_loss = criterion_cls(cls_out[attn_mask], cls_targets[attn_mask])
    # test masking: print for every item in the batch the last non masked value to check if they are one
    for i in range(cls_targets.size()[0]):
        print(cls_targets[i, attn_mask[i]].long()[-1])
    # Regression loss

    # Classification loss
    # reg_loss = criterion_reg(reg_out[y_mask], y[y_mask])
     # Example target: 1 if point exists, else 0

    # total_loss = (1-cls_weigth)*reg_loss + cls_weigth*cls_loss
    # return total_loss

compute_loss(reg_out,cls_out, y, y_mask, fixation_len)

tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tens

In [4]:
print(cls_out.shape)
print(y_mask.shape)

torch.Size([128, 14, 1])
torch.Size([128, 14])
